name: dar_mahaleh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  persistent_bottom_nav_bar_v2: ^4.2.6
  permission_handler: ^10.2.0
  fl_chart: ^0.55.2
  device_preview: ^1.1.0
  pin_code_fields: ^7.4.0
  flutter_typeahead: ^4.1.1
  dio: ^4.0.6
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6
  awesome_dialog: ^3.0.2
  geolocator: ^9.0.2 
  textfield_tags: ^2.0.2
  flutter_map: ^3.0.0
  location: ^4.4.0
  better_player: ^0.0.83
  bubble: ^1.2.1
  # mapbox_gl: ^0.16.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: yekan
      fonts:    
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
          weight: 700    
  assets:
    - assets/
    - assets/images/

